# 使用 GitHub Action 來解決手動同步到 Gitee 的問題
# 效果：github repo 代碼更新之後，會自動同步至 gitee
# 使用到的 GitHub Action：https://github.com/Yikun/hub-mirror-action

# This is a basic workflow to help you get started with Actions

name: gitee-mirror<sync2gitee.com>

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - '*'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/mengshukeji
        dst: gitee/mengshukeji
        # 這里請填寫與gitee上公鑰匹配的的 ssh private key，參見：https://gitee.com/profile/sshkeys
        # 填寫地址：https://github.com/ly525/luban-h5/settings/secrets
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        # 這里請填寫 gitee的令牌，參見：https://gitee.com/profile/personal_access_tokens
        # 填寫地址：https://github.com/ly525/luban-h5/settings/secrets
        dst_token: ${{ secrets.GITEE_TOKEN }}
        # 項目同步白名單，可以選擇填寫多個，以英文逗號分割
        static_list: "Luckyexcel,Luckysheet,LuckysheetDemo,LuckyexcelDemo,LuckysheetDocs,chartMix,LuckysheetServer"
        # 是否強制同步
        force_update: true
        # 賬號類型：對 luban-h5 而言是 user，因為是個人項目；如果是企業項目，請填寫 org，因為是組織下的項目
        account_type: user
